<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-G3JT38G" failures="1" tests="4" name="Test" time="39.086" errors="0" timestamp="2022-11-17T22:46:45 IST">
  <testcase classname="com.saucedemo.TestPack.TC01_VerifyLoginFunctionality" name="verifyLogin" time="0.158"/>
  <testcase classname="com.saucedemo.TestPack.TC02_VerifyLogOutFunctionality" name="verifyLogout" time="0.796"/>
  <testcase classname="com.saucedemo.TestPack.TC03_Verify_BagProduct_AddToCart_Functionality" name="verifyBagProductAddToCart" time="0.394"/>
  <testcase classname="com.saucedemo.TestPack.TC04_VerifyAllProductsAddToCartFunctionality" name="verifyAllProductsAddToCart" time="0.906">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.saucedemo.TestPack.TC04_VerifyAllProductsAddToCartFunctionality.verifyAllProductsAddToCart(TC04_VerifyAllProductsAddToCartFunctionality.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductsAddToCart -->
</testsuite> <!-- Test -->
